teams:
  "Atlanta Hawks":
    "conference": "Eastern"
    "color": "#e03a3e"
    "url": "https://a.espncdn.com/i/teamlogos/nba/500/atl.png"
  "Boston Celtics":
    "conference": "Eastern"
    "color": "#007a33"
    "url": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/bos.png"
  "Brooklyn Nets":
    "conference": "Eastern"
    "color": "#000000"
    "url": "https://a.espncdn.com/i/teamlogos/nba/500/bkn.png"
  "Charlotte Hornets":
    "conference": "Eastern"
    "color": "#1d1160"
    "url": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/cha.png"
  "Chicago Bulls":
    "conference": "Eastern"
    "color": "#ce1141"
    "url": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/chi.png"
  "Cleveland Cavaliers":
    "conference": "Eastern"
    "color": "#6f263d"
    "url": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/cle.png"
  "Dallas Mavericks":
    "conference": "Western"
    "color": "#00538c"
    "url": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/dal.png"
  "Denver Nuggets":
    "conference": "Western"
    "color": "#0E2240"
    "url": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/den.png"
  "Detroit Pistons":
    "conference": "Eastern"
    "color": "#006bb6"
    "url": "https://a.espncdn.com/i/teamlogos/nba/500/det.png"
  "Golden State Warriors":
    "conference": "Western"
    "color": "#fdb927"
    "url": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/gs.png"
  "Houston Rockets":
    "conference": "Western"
    "color": "#ce1141"
    "url": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/hou.png"
  "Indiana Pacers":
    "conference": "Eastern"
    "color": "#002d62"
    "url": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/ind.png"
  "Los Angeles Clippers":
    "conference": "Western"
    "color": "#ed174c"
    "url": "https://a.espncdn.com/i/teamlogos/nba/500/lac.png"
  "Los Angeles Lakers":
    "conference": "Western"
    "color": "#FDB927"
    "url": "https://a.espncdn.com/i/teamlogos/nba/500/lal.png"
  "Memphis Grizzlies":
    "conference": "Western"
    "color": "#5d76a9"
    "url": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/mem.png"
  "Miami Heat":
    "conference": "Eastern"
    "color": "#98002e"
    "url": "https://a.espncdn.com/i/teamlogos/nba/500/mia.png"
  "Milwaukee Bucks":
    "conference": "Eastern"
    "color": "#00471b"
    "url": "https://a.espncdn.com/i/teamlogos/nba/500/mil.png"
  "Minnesota Timberwolves":
    "conference": "Western"
    "color": "#0c2340"
    "url": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/min.png"
  "New Orleans Pelicans":
    "conference": "Western"
    "color": "#002b5c"
    "url": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/3.png"
  "New York Knicks":
    "conference": "Eastern"
    "color": "#f58426"
    "url": "https://a.espncdn.com/i/teamlogos/nba/500/ny.png"
  "Oklahoma City Thunder":
    "conference": "Western"
    "color": "#007ac1"
    "url": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/okc.png"
  "Orlando Magic":
    "conference": "Eastern"
    "color": "#0077c0"
    "url": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/19.png"
  "Philadelphia 76ers":
    "conference": "Eastern"
    "color": "#006bb6"
    "url": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/phi.png"
  "Phoenix Suns":
    "conference": "Western"
    "color": "#1d1160"
    "url": "https://a.espncdn.com/i/teamlogos/nba/500/phx.png"
  "Portland Trail Blazers":
    "conference": "Western"
    "color": "#e03a3e"
    "url": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/por.png"
  "Sacramento Kings":
    "conference": "Western"
    "color": "#5a2d81"
    "url": "https://a.espncdn.com/i/teamlogos/nba/500/sac.png"
  "San Antonio Spurs":
    "conference": "Western"
    "color": "#000000"
    "url": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/sa.png"
  "Toronto Raptors":
    "conference": "Eastern"
    "color": "#B4975A"
    "url": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/tor.png"
  "Utah Jazz":
    "conference": "Western"
    "color": "#002b5c"
    "url": "https://assets.stickpng.com/images/58419bb6a6515b1e0ad75a55.png"
  "Washington Wizards":
    "conference": "Eastern"
    "color": "#e31837"
    "url": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/wsh.png"